### ISSUE TITLE
use guide

### ISSUE THREAD

**Issue by rickshaw5724** [TripleHelixProgramming/HelixNavigator#9]
Sorry again to open an issue. Not sure how else to ask this.
My programmer has used the Helix Navigator to set up some way points and obstacles, but sadly we can't figure out how to generate the output coordinates data to use in the class that extends path.
Do you use export it somehow? Maybe the generate button puts a file somewhere?
Thanks, in advance.

**Comment by jlbabilino** [comment]
Until I actually add this, here's a quick summary:

- Always use custom waypoints. The other ones don't work and need to be removed.
- The first waypoint must have a control interval count of 0. The rest can just be around 40. Basically, this number defines how much resolution the solver uses for the segment leading up to the waypoint. Higher makes a smoother trajectory, but takes longer to compute. All you really ever need is about 40 though. The first waypoint doesn't have a segment leading up, that's why it's 0.
- The first and last waypoint must have a velocity constraint of zero. To do this, right click each one and click "Edit". Then check the boxes that say "Velocity X Constrained," "Velocity Y Constrained," "Velocity Magnitude Constrained," and "Angular Velocity Constrained." This is because the robot needs to start out stopped and end stopped.
- Clicking `Generate` takes a bit of time but once it's done, it saves the optimized trajectory within the app.
- After generation, you can animate the trajectory with the slider bar and the `Animate` button.
- To export it to your robot code, click the export button, then save the json in the robot code's `deploy` directory.
- Here's an example of how to use it within WPILib robot code:
  - [Trajectory](https://github.com/TripleHelixProgramming/ChargedUp/blob/main/src/main/include/util/Trajectory.hpp)
  - [TrajectoryManager](https://github.com/TripleHelixProgramming/ChargedUp/blob/main/src/main/cpp/util/TrajectoryManager.cpp)

**Comment by rickshaw5724** [comment]
Thanks for your help. We also received an update indicating this only works in Linux. Our freshmen programmer was able to get this working in WSL (windows system for Linux), and with your suggestions are now able to get the desired output.
Thanks much for your help!

**Comment by jlbabilino** [comment]
Very interesting, I didn't know it would work in WSL. If you or anyone wants to add instructions for that, that would be awesome.

**Comment by rickshaw5724** [comment]
Sorry I have not had time to add the details of how we were able to get the
app to work from Windows Subsystem for Linux. I need to talk to one of our
programmers that made that work.
I do have another question, that another one of our programmers also asked
in Discord. We wanted to know what your team does to convert the Json
trajectory file to the sets of coordinates needed by the class that extends
Path.
